### ISSUE TITLE
Receiving any debuginformation

### ISSUE THREAD

**Issue by ESEEG** [talvbansal/laravel-ms-teams-notification-channel#5]
Hi,
for testing purposes I copy pasted your democode into my environment. I nether get any errors displayed nor the demomessage shows up in teams. 
I tested my webhook-url via windows cli, everything works as it should.
Is it possible receiving any information about what is (not) going on?  
Laravel 6
Composer 1.9.3

**Comment by talvbansal** [comment]
Hey, 

Thanks for checking this out, I've thrown together an example repo that I've just tested and can get posting to a new team channel i've made.

https://github.com/talvbansal/ms-teams-testing

if you clone the project down, 

```bash
cp .env.example .env
touch database/database.sqlite
php artisan migrate --seed
```

Edit the .env file and update the `MS_TEAMS_WEBHOOK_URL` key to be your incoming webook url then run `php artisan serve` you should be able to log in using `test@test.com : password` and send a notification from the dashboard.

Whilst I know that's not entirely what you've asked for I hope a working example will be useful. Just check that your `config/services.php` has been updated

As far as debugging you could try adding a logging statement like.

```
\Log::debug(json_encode($payload));
```
In the following file

https://github.com/talvbansal/laravel-ms-teams-notification-channel/blob/85302bf0e6607b12a5fdcd5eba4ab64281dfe7c8/src/MsTeamsChannel.php#L93

(/vendor/talvbansal/laravel-ms-teams-notification-channel/src/MsTeamsChannel.php) to see the raw request payload being generated and comparing that to the one in your windows cli.

Hopefully this will help, please let me know how you get on.

Talv

**Comment by talvbansal** [comment]
@ESEEG did the above help at all?

**Comment by ESEEG** [comment]
Hi Talv,
you really helped me. Turns out I obviously didn't call the classes at all. No wonder why I didn't receive any error logs. I should have learned a bit more about classes in general. Sorry for that and thank you for your outstanding support!

**Comment by talvbansal** [comment]
No problem at all glad you got it sorted, if you can see any ways to improve the package at all please do let me know!
